### ISSUE TITLE
svg?

### ISSUE THREAD

**Issue by ser** [iMattPro/abbc3#47]
What do you think about adding support for .svg icons?

**Comment by VSEphpbb** [comment]
SVG, no. PNG, yes. i would love to have all the icons replaced by bigger 64px PNGs. Problem is I can't find any free icon sets that would cover everything

**Comment by dark-1** [comment]
Can you atleast add support for PNG and SVG , like `<BBcode>.png` & `<BBcode>.svg` instead of just `<BBcode>.gif` ?
Highest precedence from top to down :
1. `<BBcode>.svg`
2. `<BBcode>.png`
3. `<BBcode>.gif`

Best regards 👍

**Comment by GwynethLlewelyn** [comment]
I've just come across this opened issue today; in fact, I was looking for some way to change those horribly blurry icons (see also issue #48) to something modern and cool-looking — such as (why not?) Font Awesome, or anything else which looks cool, modern, and, most importantly, _not_ blurry.

It seems from the code that only `.gif` files are supported, although the 'magic' that does that is simple to change; for the 'official' 3.2.2 version, it's on `core/bbcodes_display.php`, around line 74:

```php
$bbcode_img = 'abbc3/images/icons/' . strtolower(rtrim($row['bbcode_tag'], '=')) . '.gif';
```

To be more precise, the code that follows that is a bit more intricate (because of the many replacement possibilities, e.g. for the ABB3 buttons, for custom BBCode buttons, etc.), but it's hardly complex to change.

Personally, because of its ability to scale so well, whatever the screen resolution (or if the screen is Retina or not), I'd favour SVG over PNG, especially because other phpBB plugins have done the same... GIF still has its uses for low-rez animated graphics, but it's time to move on...

**Comment by iMattPro** [comment]
As mentioned before, the problem isn't changing to SVG or PNg or anything. It's actually finding a decent icon set that can be used to replace the current one. If anyone can show me a free to use and distribute set of SVG icons that will cover all the BBCodes in ABBC3 and phpBB, then I'd happily change it.

**Comment by GwynethLlewelyn** [comment]
@iMattPro, I'm so glad to know that you're on top of the issue!

Speaking strictly for myself, I don't care to change _all_ BBCodes in phpBB & ABBC3; why go for 'perfection' (which might be impossible, unless someone spends their time redrawing all the possibly existing icons by hand), when you may get _many_ of those BBCodes readily from lots of sources, and, well, stick to existing GIF files for those that are not easy to find? This is my own theory, of course, I can imagine that as the author of a widely-used plugin you require more than 'just a few' replacement images.

Anyway, I'd suggest that you take a look at https://iconify.design/ — they pull free icons from dozens of libraries out there, and join them under a single repository; icons are provided as fonts or SVGs; no need to download them, you can simply use their API (which will provide all icons actually being _used_ on-demand, not the _whole_ palette); and they have 40,000+ icons to choose from, which I believe will cover most of the BBCodes...

All that they require is attributing the actual icon foundries (as said, their collection only includes those that have free licenses), most by attribution, some not even that — for instance, https://icons8.com, which has dozens of thousands of icons just on their own, have a special [OpenSource license](https://icons8.com/license) where they even drop the attribution requirement for well-known, reputable, open source projects (such as phpBB...).

The clear and simple icons used here on GitHub — not only on the editor, but pretty much everywhere in the site — are also [released for free under a MIT license](https://github.com/primer/octicons/). Many are also available [via the Iconify API](https://iconify.design/icon-sets/octicon/) (but not the latest version, I think).

I'm personally fond of [FontAwesome's free range of icons](https://fontawesome.com/icons?d=gallery&m=free) (a new version is due soon), available as a font and/or SVG images. There might be just around 1,500 or so icons, but there is a cool thing about them: [you can easily stack icons](https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons), thus giving you many more options, without the need of hiring a graphics designer to modify icons to suit a particular purpose. On the downside, FontAwesome is a bit confusing to handle: you can just load the required JS/CSS over their CDN, _but_ you'll be limited to 10K downloads per month or so (on the free plan), which would not be enough for the vast phpBB community; _however_, these fonts and/or SVGs can be self-hosted (there are some tricks to do that, but [they're well-documented](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself)).

I'd be surprised if all the above will not be enough to cover all your needs, but I imagine that it will certainly go a long way of providing _most_ of the required icons — leaving the odd exception out. Perhaps the main issue will be to 'mix and match' the many different sets of icons to give a consistent look (e.g. some icons might be transparent, others have a white background, some are solid, some have thin outlines, and so forth) — there might not be a _single_ set with a consistent look that provides _all_ icons for phpBB + ABBC3. Then again, we don't have that with the _current_ selection of GIF files, either...

**Comment by iMattPro** [comment]
Thanks for the recommendations. A future update will have SVG and PNG upgraded icons.

https://github.com/iMattPro/abbc3/commit/e1df41f28ca2e60e4dba14ea4ee2a1505c0792a5

**Comment by GwynethLlewelyn** [comment]
And now we have them! Thank you so much 😸
