### ISSUE TITLE
Wrong path to BBCode images

### ISSUE THREAD

**Issue by sutrus** [iMattPro/abbc3#61]
I use: phpBB 3.3.2 / extension abbc 3.3, sheer knowledgebase

If phpbb generates a path e.g. phpbbforum/app.php/knowledgebase/posting?mode=edit&id=1&k=5 (knowledgebase extension),
where the editor opens on the page, BBCode images are not displayed because the path to the images is incorrect.
The link to the button image is ./ext/vse/abbc3/images/icons/bold.png
The error is in the dot at the beginning.
I changed the file: bbcode_display.php line 154
`$icons[basename($path, `".{$this->config['abbc3_icons_type']}")]` = $path;`
`$icons[basename($path, ".{$this->config['abbc3_icons_type']}")] = preg_replace('/^./', '', $path);`

Tested on localhost and functional forum, but I don't know if it's okay.

**Comment by iMattPro** [comment]
That is not the right way to fix it but you can use that hack if it works for you until ABBC3 fixes this.

Fixed cf64787fff2a8984971c543ddc5f3ed52ce76d13
