### ISSUE TITLE
[Bug] Advanced BBcodes

### ISSUE THREAD

**Issue by FeelsBadMan1** [iMattPro/abbc3#71]
Dear iMattPro,
I added this Extention to my Forum and noticed, that some of these BBcpdes not where working. I read the faq where steps to solve this are listed. However i not got Terminalaccess to my Forum so i did the Database option.
deleting the given enteties not solved the issure at all. It also says me to wait but i dont really know how long i should wait and if i need to reenable the board like you do if you run terminal commands.

**Comment by iMattPro** [comment]
Support is here https://www.phpbb.com/customise/db/extension/advanced_bbcode_box/support
